src/TravelBook.Web/ViewModels/TravelViewModels/TravelViewModel.cs
using TravelBook.Core.ProjectAggregate;

namespace TravelBook.Web.ViewModels.TravelViewModels;

public class TravelViewModel
{
    public int Id { get; set; }
    public Place Place { get; private set; }
    public DateTime? DateStartTravel { get; set; }
    public DateTime? DateFinishTravel { get; set; }
}

src/TravelBook.Web/Controllers/TravelsController.cs
using AutoMapper;
using TravelBook.Core.Events;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TravelBook.Core.ProjectAggregate;
using TravelBook.Web.ViewModels.TravelViewModels;

namespace TravelBook.Web.Controllers;

public class TravelsController : BaseController
{
    private readonly ILogger<TravelsController> _logger;
    private readonly ITravelRepository _travelRepository;
    public TravelsController(UserManager<IdentityUser> userManager,
                             ILogger<TravelsController> logger,
                             IMapper mapper,
                             IMediator mediator,
                             ITravelRepository travelRepository)
                             : base(userManager, mapper, mediator)
    {
        _logger = logger;
        _travelRepository = travelRepository;
    }

    [HttpGet]
    public async Task<IActionResult> All()
    {
        var travels = await _travelRepository.GetAllUserTravels(UserId);
        var travelsModel = _mapper.Map<IEnumerable<TravelViewModel>>(travels);
        return View(travelsModel);
    }

    [HttpGet]
    public IActionResult Create()
    {
        ViewData["userId"] = UserId;
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(NewTravelViewModel model)
    {
        if (ModelState.IsValid)
        {
            Travel newTravel = _mapper.Map<Travel>(model);
            await _travelRepository.Add(newTravel);
            return RedirectToAction(nameof(All));
        }
        return View(model);
    }

    public async Task<IActionResult> Delete([FromQuery] int travelId)
    {
        return await ControllerAction<int, Travel, NullReferenceException>(

                travelId,

                async (id) => await _travelRepository.GetTravelById(id),

                (Travel travel) =>
                {
                    var travelModel = _mapper.Map<TravelDeleteViewModel>(travel);
                    return View(travelModel);
                });
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed([FromForm] int travelId)
    {

        return await ControllerAction<int, Travel, NullReferenceException>(

                travelId,

                async (id) => await _travelRepository.GetTravelById(id),

                async (Travel travel) =>
                {
                    int[] albumsId = travel.PhotoAlbums.Select(pa => pa.Id).ToArray();
                    await _mediator.Publish(new TravelDeletedDomainEvent(UserId, travel.Id, albumsId));
                    await _travelRepository.Delete(travel);
                    return RedirectToAction(nameof(All));
                });
    }
}

src/TravelBook.Web/Views/Travels/All.cshtml
@using TravelBook.Web.Controllers
@using TravelBook.Web.Service

@model IEnumerable<TravelBook.Web.ViewModels.TravelViewModels.TravelViewModel>

@{
    ViewBag.Title = "My Travels";
}




<table class="table">
    <thead>
        <tr>
            <th>
                Place
            </th>
            <th>
                Period
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>@item.Place.Country, @item.Place.City</td>
            <td>
                @item.DateStartTravel.Value.ToShortDateString() - @item.DateFinishTravel.Value.ToShortDateString()
            </td>
            <td>
                @Html.ActionLink("Articles", nameof(ArticlesController.TravelArticles),
                                 nameof(ArticlesController).CutController(),
                                 new { travelId=item.Id }) |
                @Html.ActionLink("Photoalbums", nameof(PhotoAlbumsController.TravelPhotoAlbums),
                                 nameof(PhotoAlbumsController).CutController(),
                                 new { travelId=item.Id }) |
                @Html.ActionLink("Delete", nameof(TravelsController.Delete),
                                 nameof(TravelsController).CutController(),
                                 new { travelId=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

<form asp-action="Create" asp-controller="Travels" method="get">
    <input type="submit" value="Add new travel" />
</form>

src/TravelBook.Web/Views/Travels/Create.cshtml
@model TravelBook.Web.ViewModels.TravelViewModels.NewTravelViewModel

@{
    ViewBag.Title = "Add new travel";
}

<h2>New travel</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Travels" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input name="UserId" value="@ViewData["userId"]" hidden="hidden" readonly/>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateStartTravel" class="control-label"></label>
                <input asp-for="DateStartTravel" class="form-control" />
                <span asp-validation-for="DateStartTravel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateFinishTravel" class="control-label"></label>
                <input asp-for="DateFinishTravel" class="form-control" />
                <span asp-validation-for="DateFinishTravel" class="text-danger"></span>
            </div>
            <div style="margin-top:10px;">
                <button type="submit">Add travel</button>
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back to travels", nameof(TravelsController.All),
                        nameof(TravelsController).CutController())
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/TravelBook.Web/Views/Travels/Delete.cshtml
@using TravelBook.Web.ViewModels.TravelViewModels

@model TravelDeleteViewModel

@{
    ViewBag.Title = "Delete travel";
}

<h2>Are you sure you want to delete all travel data?</h2>
<hr />

<div class="col-md-4">
    <p>
        @Html.DisplayNameFor(model => model.Place)
        @Html.DisplayFor(model => model.Place)
    </p>
    <p>
        Period: @Model.DateStartTravel.Value.ToShortDateString() - @Model.DateFinishTravel.Value.ToShortDateString()
    </p>
    <p>
        @Html.DisplayNameFor(model => model.NumAlbums)
        @Html.DisplayFor(model => model.NumAlbums) pcs.
    </p>
    <p>
        @Html.DisplayNameFor(model => model.NumArticles)
        @Html.DisplayFor(model => model.NumArticles) pcs.
    </p>
</div>
<div>
    <p>
        <form asp-action="Delete" asp-controller="Travels" method="post">
            <input type="hidden" name="travelId" value="@Model.Id" />
            <input type="submit" value="Delete" class="btn btn-danger"/>
        </form>
    </p>
    <p>
        @Html.ActionLink("Back to travels", nameof(TravelsController.All),
                            nameof(TravelsController).CutController())
    </p>
</div>