src/TravelBook.Web/ViewModels/ArticleViewModels/ArticleViewModel.cs
namespace TravelBook.Web.ViewModels.ArticleViewModels;

public class ArticleViewModel
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Text { get; set; }
    public string Place { get; set; }
}

src/TravelBook.Web/Controllers/ArticlesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TravelBook.Core.ProjectAggregate;
using TravelBook.Web.ViewModels.ArticleViewModels;

namespace TravelBook.Web.Controllers;

public class ArticlesController : BaseController
{
    private readonly ILogger<ArticlesController> _logger;
    private readonly ITravelRepository _travelRepository;
    public ArticlesController(UserManager<IdentityUser> userManager,
                              ILogger<ArticlesController> logger,
                              IMapper mapper,
                              IMediator mediator,
                              ITravelRepository travelRepository)
                              : base(userManager, mapper, mediator)
    {
        _logger = logger;
        _travelRepository = travelRepository;
    }

    [HttpGet]
    public async Task<IActionResult> TravelArticles([FromQuery] int travelId)
    {
        ViewBag.TravelId = travelId;
        return await ControllerAction<int, Article, ArgumentNullException>(

                travelId,

                async (id) => await _travelRepository.GetArticlesByTravelId(id),

                (Article[] articles) =>
                {
                    ViewBag.IsEmpty = false;
                    var articlesModel = _mapper.Map<IEnumerable<ArticleViewModel>>(articles);
                    return View("~/Views/Articles/ListArticles.cshtml", articlesModel);
                },

                () =>
                {
                    ViewBag.IsEmpty = true;
                    return View("~/Views/Articles/ListArticles.cshtml");
                });
    }

    [HttpGet]
    public async Task<IActionResult> All()
    {
        return await ControllerAction<string, Article, ArgumentNullException>(

                UserId,

                async (id) => await _travelRepository.GetAllUserArticles(id),

                (Article[] articles) =>
                {
                    ViewBag.IsEmpty = false;
                    var articlesModel = _mapper.Map<IEnumerable<ArticleViewModel>>(articles);
                    return View("~/Views/Articles/ListArticles.cshtml", articlesModel);
                },

                () =>
                {
                    ViewBag.IsEmpty = true;
                    return View("~/Views/Articles/ListArticles.cshtml");
                });
    }

    [HttpGet]
    public IActionResult Create([FromQuery] int travelId)
    {
        ViewBag.TravelId = travelId;
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([FromForm] NewArticleViewModel model)
    {
        if (ModelState.IsValid)
        {
            Article newArticle = _mapper.Map<Article>(model);
            await _travelRepository.AddArticle(newArticle);
            return RedirectToAction(nameof(ArticlesController.TravelArticles), new {travelId=model.TravelId});
        }
        ViewBag.TravelId = model.TravelId;
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Edit([FromQuery] int articleId)
    {
        return await ControllerAction<int, Article, NullReferenceException>(

                articleId,

                async (id) => await _travelRepository.GetArticleById(id),

                (Article article) =>
                {
                    var articleModel = _mapper.Map<EditArticleViewModel>(article);
                    return View(articleModel);
                });
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit([FromForm] EditArticleViewModel model)
    {
        if (ModelState.IsValid)
        {
            Article newArticle = _mapper.Map<Article>(model);
            await _travelRepository.EditArticle(newArticle);
            return RedirectToAction(nameof(ArticlesController.TravelArticles), new { travelId = model.TravelId });
        }
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Delete([FromQuery] int articleId)
    {
        return await ControllerAction<int, Article, NullReferenceException>(

                articleId,

                async (id) => await _travelRepository.GetArticleById(id),

                async (Article article) =>
                {
                    await _travelRepository.RemoveArticle(article);
                    return RedirectToAction(nameof(ArticlesController.TravelArticles), new { travelId = article.TravelId });
                });
    }
}

src/TravelBook.Web/Views/Articles/Create.cshtml
@model TravelBook.Web.ViewModels.ArticleViewModels.NewArticleViewModel

@{
    ViewBag.Title = "New article";
}

<h2>New article</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Articles" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="margin-bottom:20px;">
                <input hidden="hidden" name="TravelId" value="@ViewBag.TravelId" />
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group" id="editor">
                <textarea asp-for="Text" class="form-control"></textarea>
            </div>
            <div style="margin-top:10px;">
                <button type="submit">Create</button>
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back to articles", nameof(ArticlesController.TravelArticles),
                                         nameof(ArticlesController).CutController(),
                                         new { travelId=ViewBag.TravelId })
</div>

@section Scripts {
    <script src="https://cdn.ckeditor.com/ckeditor5/35.0.1/classic/ckeditor.js"></script>
    <script>
        window.onload = function() {
            ClassicEditor
                .create( document.querySelector("#@Html.IdFor(m => m.Text)") )
                .catch( error => {
                    console.error( error );
                } );
        }
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/TravelBook.Web/Views/Articles/Edit.cshtml
@model TravelBook.Web.ViewModels.ArticleViewModels.EditArticleViewModel

@{
    ViewBag.Title = "Edit article";
}

<h2>Edit article</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Articles" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="margin-bottom:20px;">
                <input asp-for="TravelId" hidden="hidden"/>
                <input asp-for="Id" hidden="hidden"/>
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group" id="editor">
                <textarea asp-for="Text" class="form-control"></textarea>
            </div>
            <div style="margin-top:10px;">
                <button type="submit">Save</button>
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back to articles", nameof(ArticlesController.TravelArticles),
                                         nameof(ArticlesController).CutController(),
                                         new { travelId=Model.TravelId })
</div>

@section Scripts {
    <script src="https://cdn.ckeditor.com/ckeditor5/35.0.1/classic/ckeditor.js"></script>
    <script>
        window.onload = function() {
            ClassicEditor
                .create( document.querySelector("#@Html.IdFor(m => m.Text)") )
                .catch( error => {
                    console.error( error );
                } );
        }
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/TravelBook.Web/Views/Articles/ListArticles.cshtml
@using TravelBook.Web.ViewModels.ArticleViewModels

@model IEnumerable<ArticleViewModel>

@{
    ViewBag.Title = "Travel articles";
}

@if(ViewBag.IsEmpty)
{
    <label>You don't have any articles yet</label>
}
else{
	@foreach(ArticleViewModel item in Model){
		<article class="box post post-excerpt">
			<header>
				<h2><a href="#">@item.Title</a></h2>
				<p>Travel place: @item.Place</p>
			</header>
			<p>
				@Html.Raw(item.Text)	
			</p>
            <p style="margin: 0; text-align:left;">
				@Html.ActionLink("Edit", nameof(ArticlesController.Edit),
										 nameof(ArticlesController).CutController(),
										 new { articleId=item.Id }) | 
				@Html.ActionLink("Delete", nameof(ArticlesController.Delete),
										   nameof(ArticlesController).CutController(),
										   new { articleId=item.Id })
            </p>
		</article>
	}
}

@if(ViewBag.TravelId != null)
{
    <form asp-action="Create" asp-controller="Articles" method="get">
        <input hidden="hidden" name="travelId" value="@ViewBag.TravelId" />
        <input type="submit" value="Add new article" />
    </form>
}