src/TravelBook.Web/Controllers/PhotosController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TravelBook.Core.ProjectAggregate;
using TravelBook.Core.Events;
using TravelBook.Web.ViewModels.PhotoAlbumViewModels;
using Microsoft.AspNetCore.Authorization;

namespace TravelBook.Web.Controllers;

public class PhotosController : BaseController
{
    private readonly ILogger<PhotosController> _logger;
    private readonly IPhotoAlbumRepository _photoAlbumRepository;
    public PhotosController(UserManager<IdentityUser> userManager,
                            ILogger<PhotosController> logger,
                            IMapper mapper,
                            IMediator mediator,
                            IPhotoAlbumRepository photoAlbumRepository)
                            : base(userManager, mapper, mediator)
    {
        _logger = logger;
        _photoAlbumRepository = photoAlbumRepository;
    }


    [HttpGet]
    public async Task<IActionResult> Edit([FromQuery] int photoId)
    {
        return await ControllerAction<int, Photo, NullReferenceException>(

                photoId,

                async (id) => await _photoAlbumRepository.GetPhotoById(id),

                (Photo photo) =>
                {
                    var photoModel = _mapper.Map<EditPhotoViewModel>(photo);
                    return View(photoModel);
                });
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit([FromForm] EditPhotoViewModel model)
    {
        Photo updatedPhoto = _mapper.Map<Photo>(model);
        await _photoAlbumRepository.EditPhoto(updatedPhoto);
        return RedirectToAction(nameof(PhotoAlbumsController.Open),
                                nameof(PhotoAlbumsController).CutController(),
                                new { photoAlbumId = model.PhotoAlbumId });
    }

    [HttpGet]
    public async Task<IActionResult> Delete([FromQuery] int photoId)
    {
        return await ControllerAction<int, Photo, NullReferenceException>(

                photoId,

                async (id) => await _photoAlbumRepository.GetPhotoById(id),

                async (Photo photo) =>
                {
                    await _mediator.Publish(new PhotoDeletedDomainEvent(photo));

                    await _photoAlbumRepository.RemovePhotosFromAlbum(photo.PhotoAlbumId, photo);

                    return RedirectToAction(nameof(PhotoAlbumsController.Open),
                        nameof(PhotoAlbumsController).CutController(),
                        new { photoAlbumId = photo.PhotoAlbumId });
                });
    }
}

src/TravelBook.Web/Views/Photos/Edit.cshtml
@using TravelBook.Web.ViewModels.PhotoAlbumViewModels

@model EditPhotoViewModel

@{
    ViewBag.Title = "Edit photo";
}

<h2>Photo edit</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Photos" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="PhotoAlbumId" />
            <input type="hidden" asp-for="ImagePath" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Place" class="control-label"></label>
                <input asp-for="Place" class="form-control" />
                <span asp-validation-for="Place" class="text-danger"></span>
            </div>
            <div style="margin-top:10px;">
                <p>
                    <input type="submit" value="Save" class="btn btn-primary" />
                </p>
            </div>
        </form>
        <div>
            <p>
                @Html.ActionLink("Back to photoalbum", nameof(PhotoAlbumsController.Open),
                                    nameof(PhotoAlbumsController).CutController(),
                                    new { photoAlbumId=Model.PhotoAlbumId })
            </p>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}