src/TravelBook.Web/ViewModels/PhotoAlbumViewModels/PhotoAlbumViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TravelBook.Web.ViewModels.PhotoAlbumViewModels;

public class PhotoAlbumViewModel
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Travel { get; set; }
    [Display(Name = "Quantity")]
    public int NumPhotos { get; set; }
}

src/TravelBook.Web/Controllers/PhotoAlbumsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TravelBook.Web.ViewModels.PhotoAlbumViewModels;
using TravelBook.Core.ProjectAggregate;
using TravelBook.Core.Events;

namespace TravelBook.Web.Controllers;

public class PhotoAlbumsController : BaseController
{
    private readonly ILogger<PhotoAlbumsController> _logger;
    private readonly IPhotoAlbumRepository _photoAlbumRepository;
    private readonly IFilesService _filesService;
    public PhotoAlbumsController(UserManager<IdentityUser> userManager,
                                 ILogger<PhotoAlbumsController> logger,
                                 IMapper mapper,
                                 IPhotoAlbumRepository photoAlbumRepository,
                                 IFilesService filesService,
                                 IMediator mediator)
                                 : base(userManager, mapper, mediator)
    {
        _logger = logger;
        _photoAlbumRepository = photoAlbumRepository;
        _filesService = filesService;
    }

    [HttpGet]
    public async Task<IActionResult> Open([FromQuery] int photoAlbumId,
                                          [FromQuery] string? returnUrl = null)
    {
        returnUrl ??= Url.Content("~/travels/all");

        return await ControllerAction<int, PhotoAlbum, NullReferenceException>(

                photoAlbumId,

                async (id) => await _photoAlbumRepository.GetAlbumById(id),

                (PhotoAlbum album) =>
                {
                    ViewBag.returnUrl = returnUrl;
                    var photoAlbumModel = _mapper.Map<OpenPhotoAlbumViewModel>(album);
                    return View(photoAlbumModel);
                });
    }

    [HttpGet]
    public async Task<IActionResult> TravelPhotoAlbums([FromQuery] int travelId)
    {
        ViewBag.TravelId = travelId;
        ViewBag.returnUrl = $"{Request.Path}{Request.QueryString}";

        return await ControllerAction<int, PhotoAlbum, ArgumentNullException>(

                travelId,

                async (id) => await _photoAlbumRepository.GetTravelPhotoAlbums(id),

                (PhotoAlbum[] albums) =>
                {
                    ViewBag.IsEmpty = false;
                    var photoAlbumsModel = _mapper.Map<IEnumerable<PhotoAlbumViewModel>>(albums);
                    return View("~/Views/PhotoAlbums/ListPhotoAlbums.cshtml", photoAlbumsModel);
                },

                () => {
                    ViewBag.IsEmpty = true;
                    return View("~/Views/PhotoAlbums/ListPhotoAlbums.cshtml");
                });
    }

    [HttpGet]
    public async Task<IActionResult> All()
    {
        ViewBag.returnUrl = $"{Request.Path}{Request.QueryString}";
        return await ControllerAction<string, PhotoAlbum, ArgumentNullException>(

                UserId,

                async (id) => await _photoAlbumRepository.GetAllUserPhotoAlbums(id),

                (PhotoAlbum[] albums) =>
                {
                    ViewBag.IsEmpty = false;
                    var photoAlbumsModel = _mapper.Map<IEnumerable<PhotoAlbumViewModel>>(albums);
                    return View("~/Views/PhotoAlbums/ListPhotoAlbums.cshtml", photoAlbumsModel);
                },

                () => {
                    ViewBag.IsEmpty = true;
                    return View("~/Views/PhotoAlbums/ListPhotoAlbums.cshtml");
                });
    }


    [HttpGet]
    public IActionResult UploadPhotosToAlbum([FromQuery] int photoAlbumId)
    {
        ViewData["photoAlbumId"] = photoAlbumId;
        return View();
    }
   
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> UploadPhotosToAlbum([FromForm] IFormFileCollection images,
                                                         [FromForm] int photoAlbumId)
    {
        return await ControllerAction<int, PhotoAlbum, NullReferenceException>(

                photoAlbumId,

                async (id) => await _photoAlbumRepository.GetAlbumById(id),

                async (PhotoAlbum album) =>
                {
                    Photo[] uploadedPhotos = await _filesService.UploadPhotos(images, UserId, album.Id);
                    await _photoAlbumRepository.AddPhotosToAlbum(album, uploadedPhotos);
                    return RedirectToAction(nameof(Open), new { photoAlbumId = photoAlbumId });
                });
    }

    [HttpGet]
    public IActionResult Create([FromQuery] int travelId, 
                                [FromQuery] string? returnUrl = null)
    {
        ViewBag.TravelId = travelId;
        ViewBag.returnUrl = returnUrl;
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([FromForm] string title, [FromForm] int travelId)
    {
        PhotoAlbum newAlbum = new PhotoAlbum(title, travelId);
        await _photoAlbumRepository.Add(newAlbum);
        await _mediator.Publish(new PhotoAlbumAddedDomainEvent(newAlbum, UserId));
        return RedirectToAction(nameof(TravelPhotoAlbums), new { travelId = travelId });
    }


    public async Task<IActionResult> Delete(int photoAlbumId, string? returnUrl = null)
    {
        returnUrl ??= Url.Content("~/travels/all");

        return await ControllerAction<int, PhotoAlbum, NullReferenceException>(

                photoAlbumId,

                async (id) => await _photoAlbumRepository.GetAlbumById(id),

                (PhotoAlbum album) =>
                {
                    ViewBag.returnUrl = returnUrl;
                    var photoAlbumModel = _mapper.Map<PhotoAlbumViewModel>(album);
                    return View(photoAlbumModel);
                });
    }


    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int photoAlbumId, string returnUrl)
    {
        return await ControllerAction<int, PhotoAlbum, NullReferenceException>(

                photoAlbumId,

                async (id) => await _photoAlbumRepository.GetAlbumById(id),

                async (PhotoAlbum album) =>
                {
                    await _photoAlbumRepository.Delete(album);
                    await _mediator.Publish(new PhotoAlbumDeletedDomainEvent(album));
                    return LocalRedirect(returnUrl);
                });
    }

}

src/TravelBook.Web/Views/PhotoAlbums/Create.cshtml
@using TravelBook.Web.Controllers
@using TravelBook.Web.Service

@{
    ViewBag.Title = "Create album";
}

<h2>Create new photoalbum</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="PhotoAlbums" method="post">
            <div class="form-group">
                <label class="form-label">Сome up with an interesting title for the album: </label>
                <input name="title" class="form-control" />
                <input hidden="hidden" name="travelId" value="@ViewBag.TravelId" />
            </div>
            <div style="margin-top:10px;">
                <p>
                    <input type="submit" value="Create" class="btn btn-primary" />
                </p>
            </div>
        </form>
        <div>
            <p>
                <a href="@ViewBag.returnUrl">Back to albums</a>
            </p>
        </div>
    </div>
</div>

src/TravelBook.Web/Views/PhotoAlbums/Delete.cshtml
@using TravelBook.Web.ViewModels.PhotoAlbumViewModels

@model PhotoAlbumViewModel

@{
    ViewBag.Title = "Delete album";
}

<h2>Are you sure you want to delete this photoalbum?</h2>
<hr />

<div class="col-md-4">
    <p>
        @Html.DisplayNameFor(model => model.Travel): 
        @Html.DisplayFor(model => model.Travel)
    </p>
    <p>
        @Html.DisplayNameFor(model => model.Title):
        @Html.DisplayFor(model => model.Title)
    </p>
    <p>
        @Html.DisplayNameFor(model => model.NumPhotos):
        @Html.DisplayFor(model => model.NumPhotos) photos
    </p>
</div>
<div>
    <p>
        <form asp-action="Delete" asp-controller="PhotoAlbums" method="post">
            <input type="hidden" name="photoAlbumId" value="@Model.Id" />
            <input type="hidden" name="returnUrl" value="@ViewBag.returnUrl" />
            <input type="submit" value="Delete" class="btn btn-danger" />
        </form>
    </p>
    <p>
        <a href="@ViewBag.returnUrl">Back to albums</a>
    </p>
</div>

src/TravelBook.Web/Views/PhotoAlbums/ListPhotoAlbums.cshtml
@using TravelBook.Web.ViewModels.PhotoAlbumViewModels

@model IEnumerable<PhotoAlbumViewModel>

@{
    ViewBag.Title = "Travel photoalbums";
}


@if(ViewBag.IsEmpty)
{
    <label>You don't have any albums yet</label>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Travel)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumPhotos)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>@item.Travel</td>
                <td>@item.Title</td>
                <td>@item.NumPhotos pcs.</td>
                <td>
                    @Html.ActionLink("Open", nameof(PhotoAlbumsController.Open),
                                             nameof(PhotoAlbumsController).CutController(),
                                             new { photoAlbumId=item.Id, returnUrl=ViewBag.returnUrl }) |
                    @Html.ActionLink("Delete", nameof(PhotoAlbumsController.Delete),
                                               nameof(PhotoAlbumsController).CutController(),
                                               new { photoAlbumId=item.Id, returnUrl=ViewBag.returnUrl })
                </td>
            </tr>
    }
        </tbody>
    </table>
}

@if(ViewBag.TravelId != null)
{
    <form asp-action="Create" asp-controller="PhotoAlbums" method="get">
        <input hidden="hidden" name="returnUrl" value="@ViewBag.returnUrl" />
        <input hidden="hidden" name="travelId" value="@ViewBag.TravelId" />
        <input type="submit" value="Add new photoalbum" />
    </form>
}

src/TravelBook.Web/Views/PhotoAlbums/Open.cshtml
@using TravelBook.Web.Controllers
@using TravelBook.Web.Service
@using TravelBook.Web.ViewModels.PhotoAlbumViewModels;

@model OpenPhotoAlbumViewModel

@{
    ViewBag.Title = Model.Travel;
}

<h2 style="text-align:center">@Model.Title</h2>
@{
    int cnt = 0;
    int numPhotos = Model.Photos.Count;
    @for(int i = 0; i < (Model.Photos.Count / 4) + 1; i++)
    {
        <div class="row" style="margin-top:10px;">
        @for(int j = 1; j <= 4; j++)
        {
             if (cnt == numPhotos) break;
            <div class="column">
                <img src="@Model.Photos[cnt].ImagePath" style="width:100%" onclick="openModal();currentSlide(@(cnt+1))" class="hover-shadow cursor">
                <p style="margin: 0; text-align:center;">
                @Html.ActionLink("Edit", nameof(PhotosController.Edit),
                                 nameof(PhotosController).CutController(),
                                 new { photoId=Model.Photos[cnt].Id }) |
                @Html.ActionLink("Delete", nameof(PhotosController.Delete),
                                 nameof(PhotosController).CutController(),
                                 new { photoId=Model.Photos[cnt].Id })
                </p>
            </div>
            cnt++;
        }
        </div>
    }

<div id="myModal" class="modal">
  <span class="close cursor" onclick="closeModal()">&times;</span>
  <div class="modal-content">

    @for(int i = 0; i < numPhotos; i++)
    {
        <div class="mySlides">
          <div class="numbertext">@(i+1) / @numPhotos</div>
          <img src="@Model.Photos[i].ImagePath" style="width:100%" alt="@Model.Photos[i].Title">
          <p hidden="hidden">@Model.Photos[i].Place</p>
        </div>        
    }
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>

    <div class="caption-container">
      <p id="title"></p>
      <p id="place"></p>
    </div>
  </div>
</div>
}

<form asp-action="UploadPhotosToAlbum" asp-controller="PhotoAlbums" method="get">
    <input name="photoAlbumId" value="@Model.Id" hidden="hidden" />
    <input type="submit" value="Add photos to album" />
</form>

<div>
    <p>
        <a href="@ViewBag.returnUrl">Back to albums</a>
    </p>
</div>

@section Styles {
    <link rel="stylesheet" href="~/css/photoalbum.css" asp-append-version="true" />
}
@section Scripts {
    <script src="~/js/photoalbum.js" asp-append-version="true"></script>
}

src/TravelBook.Web/Views/PhotoAlbums/UploadPhotosToAlbum.cshtml
@{
    ViewBag.Title = "Log in";
}

<div class="row">
    <div class="col-md-2">
        <section>
            <form asp-controller="PhotoAlbums" asp-action="UploadPhotosToAlbum" method="post" enctype="multipart/form-data">
                <h2>Upload photos to album</h2>
                <hr />
                <div class="form-floating">
                    <input name="images" type="file" multiple="true" />
                    <input value="@ViewData["photoAlbumId"]" name="photoAlbumId" hidden="hidden" />
                </div>
                <div style="margin-top:10px;">
                    <button type="submit">Send</button>
                </div>
            </form>
        </section>
    </div>
</div>